trigger: none
pr: none

variables:
  - group: common-vars
  - group: slack-webhooks
  - group: docker-registries
  - group: testing-placeholders
  - name: componentList
    value: "authx"
  - name: namespace
    value: $(Build.SourceVersion)-$(Build.BuildId)
  - name: kubeconfig
    value: $(Agent.TempDirectory)/ci_kubeconfig.yaml
  - name: authorName
    value: ""
  - name: authxSecret
    value: "this-is-my-little-secret"

resources:
  repositories:
    - repository: ci_templates
      type: github
      name: nalej/ci-templates
      endpoint: nalej
    - repository: scylla_deploy
      type: github
      name: nalej/scylla-deploy
      endpoint: nalej

jobs:
- job: DeployComponent
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - template: misc/variables.yaml@ci_templates

  - template: slack/build/start.yaml@ci_templates
    parameters:
      author: $(authorName)
      repository: $(Build.Repository.Name)
      branch: $(Build.SourceBranch)
      commit: $(Build.SourceVersionMessage)
      buildUrl: $(buildUrl)$(Build.BuildId)
      slackWebhook: $(slackBuilds)

  - template: k8s/yaml/render.yaml@ci_templates
    parameters:
      namespace: "__NPH_NAMESPACE"
      componentList: $(componentList)
      dockerRegistry: $(stagingDockerRegistry)
    
  - template: k8s/secrets/create.yaml@ci_templates
    parameters:
      name: authx-secret
      namespace: "__NPH_NAMESPACE"
      yamlPath: $(system.defaultWorkingDirectory)/dist/yaml/$(stagingDockerRegistry)/mngtcluster
      yamlFile: authx.secret.yaml
      contents: "{'secret': '$(placeholderAuthxSecret)'}"
    
  - template: k8s/yaml/publish.yaml@ci_templates
    parameters:
      yamlIdentifier: testing
      yamlPath: dist/yaml/$(stagingDockerRegistry)

  - template: ci/templates/download_artifact.yaml@scylla_deploy
    parameters:
      downloadPath: $(system.defaultWorkingDirectory)/dist/yaml/$(stagingDockerRegistry)
  
  - template: k8s/yaml/namespace.yaml@ci_templates
    parameters:
      namespace: $(namespace)
      yamlPath: dist/yaml/$(stagingDockerRegistry)
    
  - template: placeholders/replace_secrets.yaml@ci_templates
    parameters:
      yamlPath: dist/yaml/$(stagingDockerRegistry)
      placeholders: "$(placeholderAuthxSecret)"
      values: "$(authxSecret)"
  
  - task: DownloadSecureFile@1
    inputs:
      secureFile: ci_kubeconfig.yaml
    displayName: "Get K8S configuration file"
  
  - template: k8s/ns/create.yaml@ci_templates
    parameters:
      kubeconfig: $(kubeconfig)
      namespace: $(namespace)

  - template: k8s/resources/create.yaml@ci_templates
    parameters:
      kubeconfig: $(kubeconfig)
      platform: mngtcluster
      dockerRegistry: $(stagingDockerRegistry)
  
  - template: ci/templates/verify_deploy.yaml@scylla_deploy
    parameters:
      kubeconfig: $(kubeconfig)
      namespace: $(namespace)
  
  - template: templates/verify_deploy.yaml
    parameters:
      kubeconfig: $(kubeconfig)
      namespace: $(namespace)

  - template: k8s/logs/archive.yaml@ci_templates
    parameters:
      kubeconfig: $(kubeconfig)
      namespace: $(namespace)

  - template: k8s/ns/delete.yaml@ci_templates
    parameters:
      kubeconfig: $(kubeconfig)
      namespace: $(namespace)

  - template: k8s/yaml/render.yaml@ci_templates
    parameters:
      namespace: $(namespace)
      componentList: $(componentList)
      dockerRegistry: $(stagingDockerRegistry)
  
  - template: k8s/yaml/publish.yaml@ci_templates
    parameters:
      yamlIdentifier: staging
      yamlPath: dist/yaml/$(stagingDockerRegistry)

  - template: k8s/yaml/render.yaml@ci_templates
    parameters:
      namespace: $(namespace)
      componentList: $(componentList)
      dockerRegistry: $(productionDockerRegistry)
  
  - template: k8s/yaml/publish.yaml@ci_templates
    parameters:
      yamlIdentifier: production
      yamlPath: dist/yaml/$(productionDockerRegistry)
  
  - template: slack/build/finish.yaml@ci_templates
    parameters:
      author: $(authorName)
      repository: $(Build.Repository.Name)
      branch: $(Build.SourceBranch)
      commit: $(Build.SourceVersionMessage)
      buildUrl: $(buildUrl)$(Build.BuildId)
      slackWebhook: $(slackBuilds)
  
  - template: slack/build/failed.yaml@ci_templates
    parameters:
      author: $(authorName)
      repository: $(Build.Repository.Name)
      branch: $(Build.SourceBranch)
      commit: $(Build.SourceVersionMessage)
      buildUrl: $(buildUrl)$(Build.BuildId)
      slackWebhook: $(slackCIFailed)
