variables: 
  - group: common-vars
  - group: slack-webhooks
  - group: docker-registries
  - group: ci-service-principal
  - group: ssh-credentials
  - name: GOBIN
    value: '$(GOPATH)/bin'
  - name: GOROOT
    value: '/usr/local/go1.13'
  - name: GOPATH
    value: '$(system.defaultWorkingDirectory)/gopath'
  - name: modulePath
    value: '$(GOPATH)/src/github.com/$(Build.Repository.Name)'

resources:
  repositories:
    - repository: ci_templates
      type: github
      name: nalej/ci-templates
      endpoint: nalej
      ref: refs/tags/v1.0.3

jobs:
- job: MainWorkflow

  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - template: misc/variables.yaml@ci_templates

  - template: misc/nalej-component.yaml@ci_templates

  - template: slack/build/start.yaml@ci_templates
    parameters:
      author: $(authorName)
      repository: $(Build.Repository.Name)
      branch: $(Build.SourceBranch)
      commit: $(Build.SourceVersionMessage)
      buildUrl: $(buildUrl)$(Build.BuildId)
      slackWebhook: $(slackBuilds)

  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'Set up the Go workspace'

  - template: go/dep.yaml@ci_templates
    parameters:
      sshHostName: $(hostName)
      sshPublicKey: $(sshPublicKey)
      modulePath: $(modulePath)

  - template: go/test.yaml@ci_templates
    parameters:
      modulePath: $(modulePath)

  - template: go/gofmt.yaml@ci_templates
    parameters:
      modulePath: $(modulePath)

  - template: go/build.yaml@ci_templates
    parameters:
      modulePath: $(modulePath)
      appList: $(appList)
      version: $(version)
  
  - template: docker/login.yaml@ci_templates
    
  - template: docker/build.yaml@ci_templates
    parameters:
      modulePath: $(modulePath)
      imageList: $(imageList)
      version: edge
  
  - template: docker/push.yaml@ci_templates
    parameters:
      modulePath: $(modulePath)
      imageList: $(imageList)
      version: edge
    
  - template: docker/logout.yaml@ci_templates

  - template: slack/build/finish.yaml@ci_templates
    parameters:
      author: $(authorName)
      repository: $(Build.Repository.Name)
      branch: $(Build.SourceBranch)
      commit: $(Build.SourceVersionMessage)
      buildUrl: $(buildUrl)$(Build.BuildId)
      slackWebhook: $(slackBuilds)
  
  - template: slack/build/failed.yaml@ci_templates
    parameters:
      author: $(authorName)
      repository: $(Build.Repository.Name)
      branch: $(Build.SourceBranch)
      commit: $(Build.SourceVersionMessage)
      buildUrl: $(buildUrl)$(Build.BuildId)
      slackWebhook: $(slackCIFailed)
